import { AdminPanel } from "@veta/frontend/components/AdminPanel.tsx";
import { AlertsPanel } from "@veta/frontend/components/AlertsPanel.tsx";
import { AlgoLeaderboardPanel } from "@veta/frontend/components/AlgoLeaderboardPanel.tsx";
import { AlgoMonitor } from "@veta/frontend/components/AlgoMonitor.tsx";
import { AnalysisPanel } from "@veta/frontend/components/AnalysisPanel.tsx";
import { BasketOrderPanel } from "@veta/frontend/components/BasketOrderPanel.tsx";
// CandlestickChart and MarketDepth are handled as special cases in DashboardLayout (need props from channel context)
import { ChildOrdersPanel } from "@veta/frontend/components/ChildOrdersPanel.tsx";
import { ClientRfqPanel } from "@veta/frontend/components/ClientRfqPanel.tsx";
import { DataDepthPanel } from "@veta/frontend/components/DataDepthPanel.tsx";
import { DecisionLog } from "@veta/frontend/components/DecisionLog.tsx";
import { DemoDayPanel } from "@veta/frontend/components/DemoDayPanel.tsx";
import { DevToolsPanel } from "@veta/frontend/components/DevToolsPanel.tsx";
import { DurationLadderPanel } from "@veta/frontend/components/DurationLadderPanel.tsx";
import { EstateOverviewPanel } from "@veta/frontend/components/EstateOverviewPanel.tsx";
import { ExecutionsPanel } from "@veta/frontend/components/ExecutionsPanel.tsx";
import { GreeksSurfacePanel } from "@veta/frontend/components/GreeksSurfacePanel.tsx";
import { InstrumentAnalysisPanel } from "@veta/frontend/components/InstrumentAnalysisPanel.tsx";
import { LlmSubsystemPanel } from "@veta/frontend/components/LlmSubsystemPanel.tsx";
import { LoadGenPanel } from "@veta/frontend/components/LoadGenPanel.tsx";
import { LoadTestPanel } from "@veta/frontend/components/LoadTestPanel.tsx";
import { MarketDataSourcesPanel } from "@veta/frontend/components/MarketDataSourcesPanel.tsx";
import { MarketDepthPanel } from "@veta/frontend/components/MarketDepth.tsx";
import { MarketFeedControlPanel } from "@veta/frontend/components/MarketFeedControlPanel.tsx";
import { MarketHeatmap } from "@veta/frontend/components/MarketHeatmap.tsx";
import { MarketLadder } from "@veta/frontend/components/MarketLadder.tsx";
import { MarketMatch } from "@veta/frontend/components/MarketMatch.tsx";
import { MyPositionsPanel } from "@veta/frontend/components/MyPositionsPanel.tsx";
import { NewsSourcesPanel } from "@veta/frontend/components/NewsSourcesPanel.tsx";
import { ObservabilityPanel } from "@veta/frontend/components/ObservabilityPanel.tsx";
import { OptionPricingPanel } from "@veta/frontend/components/OptionPricingPanel.tsx";
import { OrderBlotter } from "@veta/frontend/components/OrderBlotter.tsx";
import { OrderProgressPanel } from "@veta/frontend/components/OrderProgressPanel.tsx";
import { OrderTicket } from "@veta/frontend/components/OrderTicket.tsx";
import { PlatformStatusPanel } from "@veta/frontend/components/PlatformStatusPanel.tsx";
import { PriceFanPanel } from "@veta/frontend/components/PriceFanPanel.tsx";
import { ProductBookPanel } from "@veta/frontend/components/ProductBookPanel.tsx";
import { ProductBuilderPanel } from "@veta/frontend/components/ProductBuilderPanel.tsx";
import { ResearchRadarPanel } from "@veta/frontend/components/ResearchRadarPanel.tsx";
import { RiskDashboardPanel } from "@veta/frontend/components/RiskDashboardPanel.tsx";
import { SalesWorkbenchPanel } from "@veta/frontend/components/SalesWorkbenchPanel.tsx";
import { ScenarioMatrixPanel } from "@veta/frontend/components/ScenarioMatrixPanel.tsx";
import { ScenariosPanel } from "@veta/frontend/components/ScenariosPanel.tsx";
import { ServiceHealthPanel } from "@veta/frontend/components/ServiceHealthPanel.tsx";
import { SessionReplayPanel } from "@veta/frontend/components/SessionReplayPanel.tsx";
import { SignalExplainabilityPanel } from "@veta/frontend/components/SignalExplainabilityPanel.tsx";
import { SpreadAnalysisPanel } from "@veta/frontend/components/SpreadAnalysisPanel.tsx";
import { SymbolSearchBar } from "@veta/frontend/components/SymbolSearchBar.tsx";
import { ThroughputGaugesPanel } from "@veta/frontend/components/ThroughputGaugesPanel.tsx";
import { TradeRecommendationPanel } from "@veta/frontend/components/TradeRecommendationPanel.tsx";
import { VolatilityProfilePanel } from "@veta/frontend/components/VolatilityProfilePanel.tsx";
import { VolSurfacePanel } from "@veta/frontend/components/VolSurfacePanel.tsx";
import { YieldCurvePanel } from "@veta/frontend/components/YieldCurvePanel.tsx";
import type { ComponentType } from "react";
import type { PanelId } from "./panelRegistry.ts";

type PanelComponent = ComponentType<Record<string, never>>;

const registry = new Map<PanelId, PanelComponent>();

export function registerPanel(id: PanelId, component: PanelComponent): void {
  registry.set(id, component);
}

export function getPanelComponent(id: string): PanelComponent | undefined {
  return registry.get(id as PanelId);
}

registerPanel("market-ladder", MarketLadder);
registerPanel("order-ticket", OrderTicket);
registerPanel("order-blotter", OrderBlotter);
registerPanel("child-orders", ChildOrdersPanel);
registerPanel("algo-monitor", AlgoMonitor);
registerPanel("observability", ObservabilityPanel);
// candle-chart is handled as a special case in DashboardLayout (needs incoming channel prop)
registerPanel("market-depth", MarketDepthPanel);
registerPanel("executions", ExecutionsPanel);
registerPanel("decision-log", DecisionLog);
registerPanel("market-match", MarketMatch);
registerPanel("admin", AdminPanel);
registerPanel("news", AnalysisPanel);
registerPanel("news-sources", NewsSourcesPanel);
registerPanel("order-progress", OrderProgressPanel);
registerPanel("market-heatmap", MarketHeatmap);
registerPanel("alerts", AlertsPanel);
registerPanel("option-pricing", OptionPricingPanel);
registerPanel("scenario-matrix", ScenarioMatrixPanel);
registerPanel("trade-recommendation", TradeRecommendationPanel);
registerPanel("market-data-sources", MarketDataSourcesPanel);
registerPanel("market-feed-control", MarketFeedControlPanel);
registerPanel("research-radar", ResearchRadarPanel);
registerPanel("instrument-analysis", InstrumentAnalysisPanel);
registerPanel("signal-explainability", SignalExplainabilityPanel);
registerPanel("service-health", ServiceHealthPanel);
registerPanel("platform-status", PlatformStatusPanel);
registerPanel("throughput-gauges", ThroughputGaugesPanel);
registerPanel("algo-leaderboard", AlgoLeaderboardPanel);
registerPanel("load-test", LoadTestPanel);
registerPanel("load-gen", LoadGenPanel);
registerPanel("llm-subsystem", LlmSubsystemPanel);
registerPanel("estate-overview", EstateOverviewPanel);
registerPanel("greeks-surface", GreeksSurfacePanel);
registerPanel("vol-profile", VolatilityProfilePanel);
registerPanel("yield-curve", YieldCurvePanel);
registerPanel("price-fan", PriceFanPanel);
registerPanel("demo-day", DemoDayPanel);
registerPanel("spread-analysis", SpreadAnalysisPanel);
registerPanel("duration-ladder", DurationLadderPanel);
registerPanel("vol-surface", VolSurfacePanel);
registerPanel("basket-order", BasketOrderPanel);
registerPanel("client-rfq", ClientRfqPanel);
registerPanel("sales-workbench", SalesWorkbenchPanel);
registerPanel("product-builder", ProductBuilderPanel);
registerPanel("product-book", ProductBookPanel);
registerPanel("session-replay", SessionReplayPanel);
registerPanel("risk-dashboard", RiskDashboardPanel);
registerPanel("my-positions", MyPositionsPanel);
registerPanel("symbol-search", SymbolSearchBar);
registerPanel("dev-tools", DevToolsPanel);
registerPanel("data-depth", DataDepthPanel);
registerPanel("scenarios", ScenariosPanel);
