/**
 * Market Data Service — port 5015
 *
 * Manages multiple market data source providers and per-symbol overrides.
 * Supported providers:
 *   - "synthetic"          — prices generated by market-sim (default for all symbols)
 *   - "alpha-vantage"      — Alpha Vantage GLOBAL_QUOTE for equities (5-min polling)
 *   - "alpha-vantage-fx"   — Alpha Vantage CURRENCY_EXCHANGE_RATE for FX pairs
 *   - "tiingo"             — Tiingo REST quotes for equities + FX
 *   - "polygon"            — Polygon.io WebSocket streaming + REST fallback for equities
 *   - "fred"               — FRED Treasury yield curve (not per-symbol; special endpoint)
 *
 * HTTP API:
 *   GET  /health
 *   GET  /sources                    → DataSource[]
 *   POST /sources/:id/toggle         → DataSource[] (toggle feed active state)
 *   GET  /quote/:symbol              → CachedQuote or 404
 *   GET  /overrides                  → { overrides: Record<string, string> }
 *   PUT  /overrides                  → { overrides: Record<string, string> }
 *   GET  /cache                      → debug: all cached quotes
 *   GET  /fred/yield-curve           → yield curve map
 */

import "https://deno.land/std@0.210.0/dotenv/load.ts";
import { json, corsOptions } from "../lib/http.ts";

import { alphaVantageEquityProvider } from "./providers/alpha-vantage-equity.ts";
import { alphaVantageFxProvider } from "./providers/alpha-vantage-fx.ts";
import { tiingoProvider } from "./providers/tiingo.ts";
import { openPolygonStream, polygonProvider } from "./providers/polygon.ts";
import { fetchYieldCurve, fredProvider } from "./providers/fred.ts";
import type { CachedQuote, ProviderDef } from "./providers/types.ts";

const PORT = Number(Deno.env.get("MARKET_DATA_PORT")) || 5_015;
const VERSION = Deno.env.get("COMMIT_SHA") || "dev";
const JOURNAL_URL = `http://${Deno.env.get("JOURNAL_HOST") ?? "localhost"}:${
  Deno.env.get("JOURNAL_PORT") ?? "5009"
}`;
const ALPHA_VANTAGE_KEY = Deno.env.get("ALPHA_VANTAGE_KEY") ?? "";
const POLYGON_KEY = Deno.env.get("POLYGON_KEY") ?? "";
const FRED_KEY = Deno.env.get("FRED_KEY") ?? "";
const OVERRIDES_FILE = "market_data_overrides.json";
const FEED_STATE_FILE = "market_data_feed_state.json";

// How long between polls per symbol (free tier: 25 calls/day → ~3456s per call if 1 symbol,
// but we target 5-min intervals per symbol in a round-robin queue)
const POLL_INTERVAL_MS = 5 * 60 * 1_000; // 5 minutes
const CACHE_TTL_MS = 310_000; // 310 seconds — slightly over 5 min

export interface DataSource {
  id: string;
  label: string;
  description: string;
  enabled: boolean;
  requiresApiKey: boolean;
  apiKeyConfigured: boolean;
  /** false when the feed has been globally paused by an admin */
  active: boolean;
  mode?: "polling" | "streaming";
  pollIntervalMs?: number;
}

const PROVIDERS: ProviderDef[] = [
  alphaVantageEquityProvider,
  alphaVantageFxProvider,
  tiingoProvider,
  polygonProvider,
  fredProvider,
];

/** Providers eligible for per-symbol overrides (excludes fred and polygon) */
const POLL_PROVIDERS: ProviderDef[] = PROVIDERS.filter(
  (p) => p.id !== "fred" && p.id !== "polygon",
);

let pausedSources: Set<string> = new Set();

function getSources(): DataSource[] {
  const synthetic: DataSource = {
    id: "synthetic",
    label: "Synthetic (market-sim)",
    description:
      "Simulated prices using Geometric Brownian Motion with sector correlation and regime drift",
    enabled: true,
    requiresApiKey: false,
    apiKeyConfigured: true,
    active: true,
    mode: "polling",
  };

  const providerSources: DataSource[] = PROVIDERS.map((p) => {
    const isStreaming = p.id === "polygon";
    return {
      id: p.id,
      label: p.label,
      description: p.description,
      enabled: p.apiKeyConfigured,
      requiresApiKey: p.requiresApiKey,
      apiKeyConfigured: p.apiKeyConfigured,
      active: !pausedSources.has(p.id),
      mode: isStreaming ? "streaming" : "polling",
      pollIntervalMs: isStreaming ? undefined : POLL_INTERVAL_MS,
    };
  });

  return [synthetic, ...providerSources];
}

/** symbol → sourceId */
let overrides: Map<string, string> = new Map();

async function loadOverrides(): Promise<void> {
  try {
    const text = await Deno.readTextFile(OVERRIDES_FILE);
    const data = JSON.parse(text) as Record<string, string>;
    overrides = new Map(Object.entries(data));
    console.log(
      `[market-data] Loaded ${overrides.size} overrides from ${OVERRIDES_FILE}`,
    );
  } catch {
    console.log(
      `[market-data] No overrides file found — starting with empty overrides`,
    );
  }
}

async function saveOverrides(): Promise<void> {
  try {
    const data = Object.fromEntries(overrides.entries());
    await Deno.writeTextFile(OVERRIDES_FILE, JSON.stringify(data, null, 2));
  } catch (err) {
    console.warn(
      `[market-data] Failed to persist overrides: ${(err as Error).message}`,
    );
  }
}

interface FeedStateFile {
  feedPaused?: boolean;
  pausedSources?: string[];
}

async function loadFeedState(): Promise<void> {
  try {
    const text = await Deno.readTextFile(FEED_STATE_FILE);
    const data = JSON.parse(text) as FeedStateFile;
    if (Array.isArray(data.pausedSources)) {
      pausedSources = new Set(data.pausedSources);
    } else if (data.feedPaused === true) {
      pausedSources = new Set(["alpha-vantage"]);
    }
    console.log(
      `[market-data] Feed state loaded: ${pausedSources.size} sources paused`,
    );
  } catch {
    console.log(`[market-data] No feed state file — defaulting to all active`);
  }
}

async function saveFeedState(): Promise<void> {
  try {
    const data: FeedStateFile = { pausedSources: Array.from(pausedSources) };
    await Deno.writeTextFile(FEED_STATE_FILE, JSON.stringify(data, null, 2));
  } catch (err) {
    console.warn(
      `[market-data] Failed to persist feed state: ${(err as Error).message}`,
    );
  }
}

const quoteCache = new Map<string, CachedQuote>();

let polygonTeardown: (() => void) | null = null;

function polygonSymbols(): string[] {
  return Array.from(overrides.entries())
    .filter(([_, src]) => src === "polygon")
    .map(([sym]) => sym);
}

function restartPolygonStream(): void {
  if (polygonTeardown) {
    polygonTeardown();
    polygonTeardown = null;
  }

  if (!POLYGON_KEY || pausedSources.has("polygon")) return;

  const symbols = polygonSymbols();
  if (symbols.length === 0) return;

  polygonTeardown = openPolygonStream(
    symbols,
    (quote: CachedQuote) => {
      quoteCache.set(quote.symbol, quote);
    },
    POLYGON_KEY,
  );
}

function symbolsForProvider(providerId: string): string[] {
  return Array.from(overrides.entries())
    .filter(([_, src]) => src === providerId)
    .map(([sym]) => sym);
}

const pollQueueIndices = new Map<string, number>();

function startPollLoop(): void {
  setInterval(async () => {
    for (const provider of POLL_PROVIDERS) {
      if (pausedSources.has(provider.id)) continue;
      if (!provider.apiKeyConfigured) continue;

      const symbols = symbolsForProvider(provider.id);
      if (symbols.length === 0) continue;

      const idx = pollQueueIndices.get(provider.id) ?? 0;
      const sym = symbols[idx % symbols.length];
      pollQueueIndices.set(provider.id, idx + 1);

      try {
        const quote = await provider.fetchQuote(sym, JOURNAL_URL);
        if (quote) {
          quoteCache.set(sym, quote);
        } else {
          const cached = quoteCache.get(sym);
          if (cached) quoteCache.set(sym, { ...cached, stale: true });
        }
      } catch {
        const cached = quoteCache.get(sym);
        if (cached) quoteCache.set(sym, { ...cached, stale: true });
      }
    }
  }, POLL_INTERVAL_MS);
}

function startStalenessChecker(): void {
  setInterval(() => {
    const now = Date.now();
    for (const [sym, q] of quoteCache.entries()) {
      if (!q.stale && now - q.fetchedAt > CACHE_TTL_MS) {
        quoteCache.set(sym, { ...q, stale: true });
      }
    }
  }, 30_000);
}

await loadOverrides();
await loadFeedState();

// Seed intraday history + immediate quote for alpha-vantage symbols on startup
if (ALPHA_VANTAGE_KEY) {
  const toSeed = symbolsForProvider("alpha-vantage");
  for (let i = 0; i < toSeed.length; i++) {
    setTimeout(
      () =>
        alphaVantageEquityProvider.seedHistory?.(toSeed[i], JOURNAL_URL).catch(
          () => {},
        ),
      i * 2_000,
    );
    setTimeout(
      () =>
        alphaVantageEquityProvider.fetchQuote(toSeed[i], JOURNAL_URL).then(
          (q) => {
            if (q) quoteCache.set(toSeed[i], q);
          },
        ).catch(() => {}),
      i * 1_500,
    );
  }
}

// Start Polygon stream if any symbols are configured
restartPolygonStream();

startPollLoop();
startStalenessChecker();

Deno.serve({ port: PORT }, async (req: Request): Promise<Response> => {
  const url = new URL(req.url);
  const path = url.pathname;

  if (req.method === "OPTIONS") {
    return corsOptions();
  }

  if (path === "/health" && req.method === "GET") {
    return json({
      service: "market-data",
      version: VERSION,
      status: "ok",
      overrides: overrides.size,
      cachedQuotes: quoteCache.size,
      alphaVantageConfigured: ALPHA_VANTAGE_KEY.length > 0,
      fredConfigured: FRED_KEY.length > 0,
      pausedSources: Array.from(pausedSources),
    });
  }

  // GET /sources
  if (path === "/sources" && req.method === "GET") {
    return json(getSources());
  }

  // POST /sources/:id/toggle
  const toggleMatch = path.match(/^\/sources\/([^/]+)\/toggle$/);
  if (toggleMatch && req.method === "POST") {
    const sourceId = toggleMatch[1];

    // Find provider (include synthetic as non-togglable)
    const provider = PROVIDERS.find((p) => p.id === sourceId);
    if (!provider) {
      return json(
        { error: `Source "${sourceId}" does not support toggling` },
        400,
      );
    }
    if (!provider.togglable) {
      return json(
        { error: `Source "${sourceId}" does not support toggling` },
        400,
      );
    }

    if (pausedSources.has(sourceId)) {
      pausedSources.delete(sourceId);
      console.log(`[market-data] Source "${sourceId}" resumed`);
      // Restart polygon stream if it was paused
      if (sourceId === "polygon") restartPolygonStream();
    } else {
      pausedSources.add(sourceId);
      console.log(`[market-data] Source "${sourceId}" paused`);
      // Tear down polygon stream if pausing
      if (sourceId === "polygon" && polygonTeardown) {
        polygonTeardown();
        polygonTeardown = null;
      }
    }

    await saveFeedState();
    return json(getSources());
  }

  // GET /cache (debug)
  if (path === "/cache" && req.method === "GET") {
    return json(Object.fromEntries(quoteCache.entries()));
  }

  // GET /overrides
  if (path === "/overrides" && req.method === "GET") {
    return json({ overrides: Object.fromEntries(overrides.entries()) });
  }

  // PUT /overrides
  if (path === "/overrides" && req.method === "PUT") {
    let body: { overrides: Record<string, string> };
    try {
      body = await req.json() as { overrides: Record<string, string> };
    } catch {
      return json({ error: "Invalid JSON body" }, 400);
    }
    if (!body.overrides || typeof body.overrides !== "object") {
      return json({ error: "Missing overrides object" }, 400);
    }

    // Validate source IDs — build valid set from all known providers + synthetic
    const validSources = new Set<string>([
      "synthetic",
      ...PROVIDERS.map((p) => p.id),
    ]);
    for (const [sym, src] of Object.entries(body.overrides)) {
      if (!validSources.has(src)) {
        return json({ error: `Unknown source: ${src} for symbol ${sym}` }, 400);
      }
    }

    // Update in-memory map — only keep non-synthetic overrides (synthetic is the default)
    const newOverrides = new Map<string, string>();
    for (const [sym, src] of Object.entries(body.overrides)) {
      if (src !== "synthetic") newOverrides.set(sym, src);
    }
    overrides = newOverrides;
    await saveOverrides();

    // Immediately fetch quotes for newly configured symbols (non-polygon providers)
    for (const [sym, src] of newOverrides.entries()) {
      const provider = POLL_PROVIDERS.find((p) => p.id === src);
      if (provider && provider.apiKeyConfigured && !quoteCache.has(sym)) {
        provider.fetchQuote(sym, JOURNAL_URL).then((q) => {
          if (q) quoteCache.set(sym, q);
        }).catch(() => {});
        if (provider.seedHistory) {
          provider.seedHistory(sym, JOURNAL_URL).catch(() => {});
        }
      }
    }

    // Restart polygon stream if polygon symbols changed
    restartPolygonStream();

    console.log(
      `[market-data] Overrides updated: ${overrides.size} symbols configured`,
    );
    return json({ overrides: Object.fromEntries(overrides.entries()) });
  }

  // GET /quote/:symbol
  const quoteMatch = path.match(/^\/quote\/([^/]+)$/);
  if (quoteMatch && req.method === "GET") {
    const symbol = decodeURIComponent(quoteMatch[1]).toUpperCase();
    const src = overrides.get(symbol);
    if (!src || src === "synthetic") {
      return json({
        error: `Symbol ${symbol} is not configured for a real data source`,
      }, 404);
    }

    const cached = quoteCache.get(symbol);
    if (!cached) {
      // Trigger async fetch from the correct provider
      const provider = PROVIDERS.find((p) => p.id === src);
      if (provider) {
        provider.fetchQuote(symbol, JOURNAL_URL).then((q) => {
          if (q) quoteCache.set(symbol, q);
        }).catch(() => {});
      }
      return json({
        error: `No quote available for ${symbol} yet — fetch triggered`,
      }, 404);
    }
    return json(cached);
  }

  // GET /fred/yield-curve
  if (path === "/fred/yield-curve" && req.method === "GET") {
    const curve = await fetchYieldCurve();
    return json(Object.fromEntries(curve.entries()));
  }

  return json({ error: "Not Found" }, 404);
});

console.log(`[market-data] Market Data Service running on port ${PORT}`);
