/**
 * Market Data Service — port 5015
 *
 * Manages multiple market data source providers and per-symbol overrides.
 * Currently supports:
 *   - "synthetic"      — prices generated by market-sim (default for all symbols)
 *   - "alpha-vantage"  — real-world prices from Alpha Vantage API (5-min polling)
 *
 * HTTP API:
 *   GET  /health
 *   GET  /sources                    → DataSource[]
 *   POST /sources/:id/toggle         → DataSource[] (toggle feed active state)
 *   GET  /quote/:symbol              → CachedQuote or 404
 *   GET  /overrides                  → { overrides: Record<string, string> }
 *   PUT  /overrides                  → { overrides: Record<string, string> }
 *   GET  /cache                      → debug: all cached quotes
 */

import "https://deno.land/std@0.210.0/dotenv/load.ts";

const PORT = Number(Deno.env.get("MARKET_DATA_PORT")) || 5_015;
const VERSION = Deno.env.get("COMMIT_SHA") || "dev";
const JOURNAL_URL = `http://${Deno.env.get("JOURNAL_HOST") ?? "localhost"}:${Deno.env.get("JOURNAL_PORT") ?? "5009"}`;
const ALPHA_VANTAGE_KEY = Deno.env.get("ALPHA_VANTAGE_KEY") ?? "";
const ALPHA_VANTAGE_BASE = "https://www.alphavantage.co/query";
const OVERRIDES_FILE = "market_data_overrides.json";
const FEED_STATE_FILE = "market_data_feed_state.json";

let feedPaused = false;

// How long between polls per symbol (free tier: 25 calls/day → ~3456s per call if 1 symbol,
// but we target 5-min intervals per symbol in a round-robin queue)
const POLL_INTERVAL_MS = 5 * 60 * 1_000;  // 5 minutes
const CACHE_TTL_MS = 310_000;              // 310 seconds — slightly over 5 min

const CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, POST, PUT, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type",
};

function json(data: unknown, status = 200): Response {
  return new Response(JSON.stringify(data), {
    status,
    headers: { "Content-Type": "application/json", ...CORS },
  });
}

// ── Data source definitions ───────────────────────────────────────────────────

export interface DataSource {
  id: "synthetic" | "alpha-vantage";
  label: string;
  description: string;
  enabled: boolean;
  requiresApiKey: boolean;
  apiKeyConfigured: boolean;
  /** false when the feed has been globally paused by an admin */
  active: boolean;
}

type SourceDef = Omit<DataSource, "active">;

const SOURCES: SourceDef[] = [
  {
    id: "synthetic",
    label: "Synthetic (market-sim)",
    description: "Simulated prices using Geometric Brownian Motion with sector correlation and regime drift",
    enabled: true,
    requiresApiKey: false,
    apiKeyConfigured: true,
  },
  {
    id: "alpha-vantage",
    label: "Alpha Vantage",
    description: "Real-world market data via Alpha Vantage API. Free tier: 25 API calls/day. Prices polled every 5 minutes.",
    enabled: ALPHA_VANTAGE_KEY.length > 0,
    requiresApiKey: true,
    apiKeyConfigured: ALPHA_VANTAGE_KEY.length > 0,
  },
];

/** Returns sources with runtime `active` state hydrated. */
function getSources(): DataSource[] {
  return SOURCES.map((s) => ({
    ...s,
    active: s.id === "alpha-vantage" ? !feedPaused : true,
  }));
}

// ── Override store ─────────────────────────────────────────────────────────────

/** symbol → sourceId */
let overrides: Map<string, string> = new Map();

async function loadOverrides(): Promise<void> {
  try {
    const text = await Deno.readTextFile(OVERRIDES_FILE);
    const data = JSON.parse(text) as Record<string, string>;
    overrides = new Map(Object.entries(data));
    console.log(`[market-data] Loaded ${overrides.size} overrides from ${OVERRIDES_FILE}`);
  } catch {
    console.log(`[market-data] No overrides file found — starting with empty overrides`);
  }
}

async function saveOverrides(): Promise<void> {
  try {
    const data = Object.fromEntries(overrides.entries());
    await Deno.writeTextFile(OVERRIDES_FILE, JSON.stringify(data, null, 2));
  } catch (err) {
    console.warn(`[market-data] Failed to persist overrides: ${(err as Error).message}`);
  }
}

async function loadFeedState(): Promise<void> {
  try {
    const text = await Deno.readTextFile(FEED_STATE_FILE);
    const data = JSON.parse(text) as { feedPaused: boolean };
    feedPaused = data.feedPaused === true;
    console.log(`[market-data] Feed state: paused=${feedPaused}`);
  } catch {
    console.log(`[market-data] No feed state file — defaulting to active`);
  }
}

async function saveFeedState(): Promise<void> {
  try {
    await Deno.writeTextFile(FEED_STATE_FILE, JSON.stringify({ feedPaused }, null, 2));
  } catch (err) {
    console.warn(`[market-data] Failed to persist feed state: ${(err as Error).message}`);
  }
}

// ── Quote cache ────────────────────────────────────────────────────────────────

export interface CachedQuote {
  symbol: string;
  price: number;
  volume: number;
  latestTradingDay: string;
  fetchedAt: number;
  stale: boolean;
}

const quoteCache = new Map<string, CachedQuote>();

// ── Alpha Vantage fetching ─────────────────────────────────────────────────────

async function fetchGlobalQuote(symbol: string): Promise<void> {
  if (!ALPHA_VANTAGE_KEY) return;
  try {
    console.log(`[market-data] Polling Alpha Vantage GLOBAL_QUOTE for ${symbol}`);
    const url = `${ALPHA_VANTAGE_BASE}?function=GLOBAL_QUOTE&symbol=${encodeURIComponent(symbol)}&apikey=${ALPHA_VANTAGE_KEY}`;
    const res = await fetch(url, { signal: AbortSignal.timeout(10_000) });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const data = await res.json() as Record<string, Record<string, string>>;
    const q = data["Global Quote"];
    if (!q || !q["05. price"]) {
      console.warn(`[market-data] No quote data for ${symbol} — rate limit or invalid symbol?`);
      return;
    }
    const price = parseFloat(q["05. price"]);
    const volume = parseInt(q["06. volume"] ?? "0", 10);
    const latestTradingDay = q["07. latest trading day"] ?? "";
    if (price > 0) {
      quoteCache.set(symbol, { symbol, price, volume, latestTradingDay, fetchedAt: Date.now(), stale: false });
      console.log(`[market-data] Cached ${symbol}: $${price.toFixed(4)} (${latestTradingDay})`);
    }
  } catch (err) {
    console.warn(`[market-data] Quote fetch failed for ${symbol}: ${(err as Error).message}`);
    // Mark cached entry as stale but keep the price
    const cached = quoteCache.get(symbol);
    if (cached) quoteCache.set(symbol, { ...cached, stale: true });
  }
}

async function seedIntradayHistory(symbol: string): Promise<void> {
  if (!ALPHA_VANTAGE_KEY) return;
  try {
    console.log(`[market-data] Fetching intraday history for ${symbol}`);
    const url = `${ALPHA_VANTAGE_BASE}?function=TIME_SERIES_INTRADAY&symbol=${encodeURIComponent(symbol)}&interval=1min&outputsize=compact&apikey=${ALPHA_VANTAGE_KEY}`;
    const res = await fetch(url, { signal: AbortSignal.timeout(15_000) });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const data = await res.json() as Record<string, unknown>;
    const series = data["Time Series (1min)"] as Record<string, Record<string, string>> | undefined;
    if (!series) {
      console.warn(`[market-data] No intraday data for ${symbol}`);
      return;
    }

    // Convert to candle format and post to journal
    const candles = Object.entries(series)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([timestamp, bar]) => ({
        symbol,
        interval: "1m",
        ts: new Date(timestamp).getTime(),
        open: parseFloat(bar["1. open"]),
        high: parseFloat(bar["2. high"]),
        low: parseFloat(bar["3. low"]),
        close: parseFloat(bar["4. close"]),
        volume: parseInt(bar["5. volume"] ?? "0", 10),
      }));

    if (candles.length === 0) return;

    // POST to journal seed endpoint
    const seedRes = await fetch(`${JOURNAL_URL}/candles/seed`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ symbol, candles }),
      signal: AbortSignal.timeout(15_000),
    });
    if (seedRes.ok) {
      console.log(`[market-data] Seeded ${candles.length} intraday candles for ${symbol} into journal`);
    } else {
      console.warn(`[market-data] Journal seed returned ${seedRes.status} for ${symbol}`);
    }
  } catch (err) {
    console.warn(`[market-data] Intraday seed failed for ${symbol}: ${(err as Error).message}`);
  }
}

// ── Poll loop ─────────────────────────────────────────────────────────────────

/** Returns symbols currently overridden to alpha-vantage */
function alphaVantageSymbols(): string[] {
  return Array.from(overrides.entries())
    .filter(([_, src]) => src === "alpha-vantage")
    .map(([sym]) => sym);
}

let pollQueueIndex = 0;

function startPollLoop(): void {
  setInterval(() => {
    if (feedPaused) return;
    const symbols = alphaVantageSymbols();
    if (symbols.length === 0 || !ALPHA_VANTAGE_KEY) return;
    // Round-robin: poll one symbol per interval
    const sym = symbols[pollQueueIndex % symbols.length];
    pollQueueIndex++;
    fetchGlobalQuote(sym).catch(() => {});
  }, POLL_INTERVAL_MS);
}

/** Mark cached quotes as stale if older than TTL */
function startStalenessChecker(): void {
  setInterval(() => {
    const now = Date.now();
    for (const [sym, q] of quoteCache.entries()) {
      if (!q.stale && now - q.fetchedAt > CACHE_TTL_MS) {
        quoteCache.set(sym, { ...q, stale: true });
      }
    }
  }, 30_000);
}

// ── Startup ───────────────────────────────────────────────────────────────────

await loadOverrides();
await loadFeedState();

// Seed intraday history for all configured symbols on startup (staggered)
if (ALPHA_VANTAGE_KEY) {
  const toSeed = alphaVantageSymbols();
  for (let i = 0; i < toSeed.length; i++) {
    // Stagger by 2s to avoid hitting rate limits on startup
    setTimeout(() => seedIntradayHistory(toSeed[i]).catch(() => {}), i * 2_000);
    // Also immediately fetch quote
    setTimeout(() => fetchGlobalQuote(toSeed[i]).catch(() => {}), i * 1_500);
  }
}

startPollLoop();
startStalenessChecker();

// ── HTTP Handler ──────────────────────────────────────────────────────────────

Deno.serve({ port: PORT }, async (req: Request): Promise<Response> => {
  const url = new URL(req.url);
  const path = url.pathname;

  if (req.method === "OPTIONS") return new Response(null, { status: 204, headers: CORS });

  if (path === "/health" && req.method === "GET") {
    return json({
      service: "market-data",
      version: VERSION,
      status: "ok",
      overrides: overrides.size,
      cachedQuotes: quoteCache.size,
      alphaVantageConfigured: ALPHA_VANTAGE_KEY.length > 0,
      feedPaused,
    });
  }

  // GET /sources
  if (path === "/sources" && req.method === "GET") {
    return json(getSources());
  }

  // POST /sources/:id/toggle
  const toggleMatch = path.match(/^\/sources\/([^/]+)\/toggle$/);
  if (toggleMatch && req.method === "POST") {
    const sourceId = toggleMatch[1];
    if (sourceId !== "alpha-vantage") {
      return json({ error: `Source "${sourceId}" does not support toggling` }, 400);
    }
    feedPaused = !feedPaused;
    await saveFeedState();
    console.log(`[market-data] Alpha Vantage feed ${feedPaused ? "paused" : "resumed"}`);
    return json(getSources());
  }

  // GET /cache (debug)
  if (path === "/cache" && req.method === "GET") {
    return json(Object.fromEntries(quoteCache.entries()));
  }

  // GET /overrides
  if (path === "/overrides" && req.method === "GET") {
    return json({ overrides: Object.fromEntries(overrides.entries()) });
  }

  // PUT /overrides
  if (path === "/overrides" && req.method === "PUT") {
    let body: { overrides: Record<string, string> };
    try {
      body = await req.json() as { overrides: Record<string, string> };
    } catch {
      return json({ error: "Invalid JSON body" }, 400);
    }
    if (!body.overrides || typeof body.overrides !== "object") {
      return json({ error: "Missing overrides object" }, 400);
    }

    // Validate source IDs
    const validSources = new Set(SOURCES.map((s) => s.id));
    for (const [sym, src] of Object.entries(body.overrides)) {
      if (!validSources.has(src as "synthetic" | "alpha-vantage")) {
        return json({ error: `Unknown source: ${src} for symbol ${sym}` }, 400);
      }
    }

    // Update in-memory map — only keep non-synthetic overrides (synthetic is the default)
    const newOverrides = new Map<string, string>();
    for (const [sym, src] of Object.entries(body.overrides)) {
      if (src !== "synthetic") newOverrides.set(sym, src);
    }
    overrides = newOverrides;
    await saveOverrides();

    // Immediately fetch quotes for newly configured alpha-vantage symbols
    if (ALPHA_VANTAGE_KEY) {
      for (const [sym, src] of newOverrides.entries()) {
        if (src === "alpha-vantage" && !quoteCache.has(sym)) {
          fetchGlobalQuote(sym).catch(() => {});
          seedIntradayHistory(sym).catch(() => {});
        }
      }
    }

    console.log(`[market-data] Overrides updated: ${overrides.size} symbols configured`);
    return json({ overrides: Object.fromEntries(overrides.entries()) });
  }

  // GET /quote/:symbol
  const quoteMatch = path.match(/^\/quote\/([^/]+)$/);
  if (quoteMatch && req.method === "GET") {
    const symbol = decodeURIComponent(quoteMatch[1]).toUpperCase();
    const src = overrides.get(symbol);
    if (!src || src === "synthetic") {
      return json({ error: `Symbol ${symbol} is not configured for a real data source` }, 404);
    }
    const cached = quoteCache.get(symbol);
    if (!cached) {
      // Trigger async fetch but return 404 for now (will be available on next call)
      fetchGlobalQuote(symbol).catch(() => {});
      return json({ error: `No quote available for ${symbol} yet — fetch triggered` }, 404);
    }
    return json(cached);
  }

  return new Response("Not Found", { status: 404, headers: CORS });
});

console.log(`[market-data] Market Data Service running on port ${PORT}`);
