import type { BondDef } from "./bondUniverseTypes.ts";

/**
 * Hand-curated bond universe: 10 US Treasuries (on-the-run curve) + 5
 * investment-grade corporate bonds. Coupon rates and initial yields
 * approximate a realistic post-2024 environment (Fed funds ~5.25%, IG corp
 * spread ~80-120bp over Treasuries). Shared between the backend market-sim
 * and the frontend order ticket so both read one source instead of two
 * hand-duplicated copies.
 *
 * totalPeriods = maturityYears x periodsPerYear (semi-annual = 2)
 */

function maturityFromPeriods(totalPeriods: number, periodsPerYear = 2): string {
  const yearsFromNow = totalPeriods / periodsPerYear;
  const d = new Date();
  d.setFullYear(d.getFullYear() + Math.floor(yearsFromNow));
  d.setMonth(d.getMonth() + Math.round((yearsFromNow % 1) * 12));
  return d.toISOString().slice(0, 10);
}

export const CURATED_BONDS: BondDef[] = [
  {
    isin: "US912796ZR07",
    symbol: "US3M",
    description: "3-Month US Treasury Bill",
    couponRate: 0.0,
    maturityDate: maturityFromPeriods(1, 4),
    periodsPerYear: 4,
    totalPeriods: 1,
    creditRating: "AAA",
    issuer: "UST",
    initialYield: 0.0532,
    faceValue: 1000,
  },
  {
    isin: "US912796ZS80",
    symbol: "US6M",
    description: "6-Month US Treasury Bill",
    couponRate: 0.0,
    maturityDate: maturityFromPeriods(1),
    periodsPerYear: 2,
    totalPeriods: 1,
    creditRating: "AAA",
    issuer: "UST",
    initialYield: 0.0528,
    faceValue: 1000,
  },
  {
    isin: "US912828ZT01",
    symbol: "US1Y",
    description: "1-Year US Treasury Note",
    couponRate: 0.05,
    maturityDate: maturityFromPeriods(2),
    periodsPerYear: 2,
    totalPeriods: 2,
    creditRating: "AAA",
    issuer: "UST",
    initialYield: 0.051,
    faceValue: 1000,
  },
  {
    isin: "US91282CKL26",
    symbol: "US2Y",
    description: "2-Year US Treasury Note",
    couponRate: 0.0475,
    maturityDate: maturityFromPeriods(4),
    periodsPerYear: 2,
    totalPeriods: 4,
    creditRating: "AAA",
    issuer: "UST",
    initialYield: 0.0488,
    faceValue: 1000,
  },
  {
    isin: "US91282CKM09",
    symbol: "US3Y",
    description: "3-Year US Treasury Note",
    couponRate: 0.045,
    maturityDate: maturityFromPeriods(6),
    periodsPerYear: 2,
    totalPeriods: 6,
    creditRating: "AAA",
    issuer: "UST",
    initialYield: 0.0462,
    faceValue: 1000,
  },
  {
    isin: "US91282CKN81",
    symbol: "US5Y",
    description: "5-Year US Treasury Note",
    couponRate: 0.0425,
    maturityDate: maturityFromPeriods(10),
    periodsPerYear: 2,
    totalPeriods: 10,
    creditRating: "AAA",
    issuer: "UST",
    initialYield: 0.0435,
    faceValue: 1000,
  },
  {
    isin: "US91282CKP38",
    symbol: "US7Y",
    description: "7-Year US Treasury Note",
    couponRate: 0.0425,
    maturityDate: maturityFromPeriods(14),
    periodsPerYear: 2,
    totalPeriods: 14,
    creditRating: "AAA",
    issuer: "UST",
    initialYield: 0.0432,
    faceValue: 1000,
  },
  {
    isin: "US91282CKQ11",
    symbol: "US10Y",
    description: "10-Year US Treasury Note",
    couponRate: 0.04375,
    maturityDate: maturityFromPeriods(20),
    periodsPerYear: 2,
    totalPeriods: 20,
    creditRating: "AAA",
    issuer: "UST",
    initialYield: 0.0445,
    faceValue: 1000,
  },
  {
    isin: "US912810TL21",
    symbol: "US20Y",
    description: "20-Year US Treasury Bond",
    couponRate: 0.0475,
    maturityDate: maturityFromPeriods(40),
    periodsPerYear: 2,
    totalPeriods: 40,
    creditRating: "AAA",
    issuer: "UST",
    initialYield: 0.048,
    faceValue: 1000,
  },
  {
    isin: "US912810TM04",
    symbol: "US30Y",
    description: "30-Year US Treasury Bond",
    couponRate: 0.04625,
    maturityDate: maturityFromPeriods(60),
    periodsPerYear: 2,
    totalPeriods: 60,
    creditRating: "AAA",
    issuer: "UST",
    initialYield: 0.0468,
    faceValue: 1000,
  },
  {
    isin: "US037833EQ73",
    symbol: "AAPL5Y",
    description: "Apple Inc. 5-Year Senior Note",
    couponRate: 0.051,
    maturityDate: maturityFromPeriods(10),
    periodsPerYear: 2,
    totalPeriods: 10,
    creditRating: "AA+",
    issuer: "Corp",
    sector: "Technology",
    initialYield: 0.052,
    faceValue: 1000,
  },
  {
    isin: "US46625HRL59",
    symbol: "JPM10Y",
    description: "JPMorgan Chase & Co. 10-Year Senior Note",
    couponRate: 0.054,
    maturityDate: maturityFromPeriods(20),
    periodsPerYear: 2,
    totalPeriods: 20,
    creditRating: "A+",
    issuer: "Corp",
    sector: "Financials",
    initialYield: 0.0555,
    faceValue: 1000,
  },
  {
    isin: "US30231GAV85",
    symbol: "XOM7Y",
    description: "Exxon Mobil Corporation 7-Year Senior Note",
    couponRate: 0.052,
    maturityDate: maturityFromPeriods(14),
    periodsPerYear: 2,
    totalPeriods: 14,
    creditRating: "AA",
    issuer: "Corp",
    sector: "Energy",
    initialYield: 0.0528,
    faceValue: 1000,
  },
  {
    isin: "US478160CG87",
    symbol: "JNJ3Y",
    description: "Johnson & Johnson 3-Year Senior Note",
    couponRate: 0.049,
    maturityDate: maturityFromPeriods(6),
    periodsPerYear: 2,
    totalPeriods: 6,
    creditRating: "AAA",
    issuer: "Corp",
    sector: "Health Care",
    initialYield: 0.0498,
    faceValue: 1000,
  },
  {
    isin: "US594918BN46",
    symbol: "MSFT5Y",
    description: "Microsoft Corporation 5-Year Senior Note",
    couponRate: 0.0505,
    maturityDate: maturityFromPeriods(10),
    periodsPerYear: 2,
    totalPeriods: 10,
    creditRating: "AAA",
    issuer: "Corp",
    sector: "Technology",
    initialYield: 0.0512,
    faceValue: 1000,
  },
];
