export type ServiceCategory = "core" | "algo" | "data" | "infra" | "observability";

export interface ServiceSpec {
  id: string;
  displayName: string;
  envPrefix: string;
  composeName: string;
  defaultPort: number;
  category: ServiceCategory;
  description: string;
  optional?: boolean;
  excludeFromGatewayHostEnv?: boolean;
  excludeFromFrontendServices?: boolean;
  alertOnDeployments?: readonly string[];
  showOnDeployments?: readonly string[];
}

export const SERVICE_REGISTRY: readonly ServiceSpec[] = [
  {
    id: "marketSim",
    displayName: "Market Sim",
    envPrefix: "MARKET_SIM",
    composeName: "market-sim",
    defaultPort: 5000,
    category: "core",
    description: "GBM price simulation & synthetic market feed",
  },
  {
    id: "ems",
    displayName: "EMS",
    envPrefix: "EMS",
    composeName: "ems",
    defaultPort: 5001,
    category: "core",
    description: "Execution management — child order routing & fills",
  },
  {
    id: "oms",
    displayName: "OMS",
    envPrefix: "OMS",
    composeName: "oms",
    defaultPort: 5002,
    category: "core",
    description: "Order management — validation, RBAC limits & routing",
  },
  {
    id: "limitAlgo",
    displayName: "Limit Algo",
    envPrefix: "LIMIT_ALGO",
    composeName: "limit-algo",
    defaultPort: 5003,
    category: "algo",
    description: "Passive limit order strategy with configurable aggression",
  },
  {
    id: "twapAlgo",
    displayName: "TWAP Algo",
    envPrefix: "TWAP_ALGO",
    composeName: "twap-algo",
    defaultPort: 5004,
    category: "algo",
    description: "Time-Weighted Average Price — uniform slice scheduling",
  },
  {
    id: "povAlgo",
    displayName: "POV Algo",
    envPrefix: "POV_ALGO",
    composeName: "pov-algo",
    defaultPort: 5005,
    category: "algo",
    description: "Percentage of Volume — tracks market participation rate",
  },
  {
    id: "vwapAlgo",
    displayName: "VWAP Algo",
    envPrefix: "VWAP_ALGO",
    composeName: "vwap-algo",
    defaultPort: 5006,
    category: "algo",
    description: "Volume-Weighted Average Price — historically-shaped slices",
  },
  {
    id: "kafkaRelay",
    displayName: "Kafka Relay",
    envPrefix: "KAFKA_RELAY",
    composeName: "kafka-relay",
    defaultPort: 5007,
    category: "observability",
    description: "Kafka → stdout relay feeding Grafana Alloy / Loki",
    optional: true,
  },
  {
    id: "userService",
    displayName: "User Service",
    envPrefix: "USER_SERVICE",
    composeName: "user-service",
    defaultPort: 5008,
    category: "infra",
    description: "Session management, RBAC token validation & trading limits",
  },
  {
    id: "journal",
    displayName: "Journal",
    envPrefix: "JOURNAL",
    composeName: "journal",
    defaultPort: 5009,
    category: "data",
    description: "Trade lifecycle store — orders, fills & OHLCV grid",
  },
  {
    id: "fixArchive",
    displayName: "FIX Archive",
    envPrefix: "FIX_ARCHIVE",
    composeName: "fix-archive",
    defaultPort: 5012,
    category: "infra",
    description: "Postgres persistence for FIX execution reports",
  },
  {
    id: "newsAggregator",
    displayName: "News Aggregator",
    envPrefix: "NEWS_AGGREGATOR",
    composeName: "news-aggregator",
    defaultPort: 5013,
    category: "data",
    description: "Pulls and tags market news for the feature engine",
  },
  {
    id: "analytics",
    displayName: "Analytics",
    envPrefix: "ANALYTICS",
    composeName: "analytics",
    defaultPort: 5014,
    category: "data",
    description: "Black-Scholes pricing, Monte Carlo scenarios & recommendations",
  },
  {
    id: "marketData",
    displayName: "Market Data",
    envPrefix: "MARKET_DATA",
    composeName: "market-data",
    defaultPort: 5015,
    category: "data",
    description: "Alpha Vantage polling & per-symbol source overrides",
  },
  {
    id: "marketDataAdapters",
    displayName: "Market Data Adapters",
    envPrefix: "MARKET_DATA_ADAPTERS",
    composeName: "market-data-adapters",
    defaultPort: 5016,
    category: "data",
    description: "Provider adapter layer between market-data and external feeds",
    excludeFromFrontendServices: true,
  },
  {
    id: "featureEngine",
    displayName: "Feature Engine",
    envPrefix: "FEATURE_ENGINE",
    composeName: "feature-engine",
    defaultPort: 5017,
    category: "data",
    description: "Per-symbol feature vector derivation from price/volume/news",
  },
  {
    id: "signalEngine",
    displayName: "Signal Engine",
    envPrefix: "SIGNAL_ENGINE",
    composeName: "signal-engine",
    defaultPort: 5018,
    category: "data",
    description: "Buy/sell/neutral signal scoring from feature vectors",
  },
  {
    id: "recommendationEngine",
    displayName: "Recommendation Engine",
    envPrefix: "RECOMMENDATION_ENGINE",
    composeName: "recommendation-engine",
    defaultPort: 5019,
    category: "data",
    description: "Trade recommendations from signals + position context",
  },
  {
    id: "scenarioEngine",
    displayName: "Scenario Engine",
    envPrefix: "SCENARIO_ENGINE",
    composeName: "scenario-engine",
    defaultPort: 5020,
    category: "data",
    description: "Deterministic scenario replay for backtests and demos",
  },
  {
    id: "icebergAlgo",
    displayName: "Iceberg Algo",
    envPrefix: "ICEBERG_ALGO",
    composeName: "iceberg-algo",
    defaultPort: 5021,
    category: "algo",
    description: "Hidden quantity — exposes only visible slice to the market",
  },
  {
    id: "sniperAlgo",
    displayName: "Sniper Algo",
    envPrefix: "SNIPER_ALGO",
    composeName: "sniper-algo",
    defaultPort: 5022,
    category: "algo",
    description: "Opportunistic aggressive fills at favourable price levels",
  },
  {
    id: "arrivalPriceAlgo",
    displayName: "Arrival Price Algo",
    envPrefix: "ARRIVAL_PRICE_ALGO",
    composeName: "arrival-price-algo",
    defaultPort: 5023,
    category: "algo",
    description: "Benchmarks execution against arrival price with slippage control",
  },
  {
    id: "llmAdvisory",
    displayName: "LLM Advisory",
    envPrefix: "LLM_ADVISORY",
    composeName: "llm-advisory",
    defaultPort: 5024,
    category: "data",
    description: "LLM-generated advisory notes for symbols (orchestrator + worker)",
    optional: true,
  },
  {
    id: "momentumAlgo",
    displayName: "Momentum Algo",
    envPrefix: "MOMENTUM_ALGO",
    composeName: "momentum-algo",
    defaultPort: 5025,
    category: "algo",
    description: "EMA crossover momentum — routes tranches on favourable price signals",
  },
  {
    id: "isAlgo",
    displayName: "IS Algo",
    envPrefix: "IS_ALGO",
    composeName: "is-algo",
    defaultPort: 5026,
    category: "algo",
    description: "Implementation Shortfall — balances market impact vs timing risk",
  },
  {
    id: "darkPool",
    displayName: "Dark Pool",
    envPrefix: "DARK_POOL",
    composeName: "dark-pool",
    defaultPort: 5027,
    category: "core",
    description: "Hidden venue with periodic crossing for size-conscious orders",
  },
  {
    id: "ccpService",
    displayName: "CCP Service",
    envPrefix: "CCP_SERVICE",
    composeName: "ccp-service",
    defaultPort: 5028,
    category: "core",
    description: "Central counterparty — novation, margin, settlement lifecycle",
  },
  {
    id: "rfqService",
    displayName: "RFQ Service",
    envPrefix: "RFQ_SERVICE",
    composeName: "rfq-service",
    defaultPort: 5029,
    category: "core",
    description: "Request-for-quote workflow with dealer responses",
  },
  {
    id: "productService",
    displayName: "Product Service",
    envPrefix: "PRODUCT_SERVICE",
    composeName: "product-service",
    defaultPort: 5030,
    category: "core",
    description: "Instrument reference data — symbols, lot sizes, contract specs",
  },
  {
    id: "replay",
    displayName: "Replay",
    envPrefix: "REPLAY",
    composeName: "replay-service",
    defaultPort: 5031,
    category: "observability",
    description: "Session recording and replay",
    optional: true,
  },
  {
    id: "riskEngine",
    displayName: "Risk Engine",
    envPrefix: "RISK_ENGINE",
    composeName: "risk-engine",
    defaultPort: 5032,
    category: "core",
    description: "Real-time pre-trade and post-trade risk checks",
  },
  {
    id: "llmWorker",
    displayName: "LLM Worker",
    envPrefix: "LLM_WORKER",
    composeName: "llm-worker",
    defaultPort: 5033,
    category: "data",
    description: "LLM inference worker consuming jobs from llm-advisory queue",
    optional: true,
    excludeFromGatewayHostEnv: true,
    excludeFromFrontendServices: true,
  },
  {
    id: "fixGateway",
    displayName: "FIX Gateway",
    envPrefix: "FIX_GATEWAY",
    composeName: "fix-gateway",
    defaultPort: 9881,
    category: "infra",
    description: "WebSocket bridge to FIX exchange",
  },
];

export function findService(predicate: (s: ServiceSpec) => boolean): ServiceSpec | undefined {
  return SERVICE_REGISTRY.find(predicate);
}

export function gatewayHostEnvBlock(): string {
  const lines: string[] = [];
  for (const svc of SERVICE_REGISTRY) {
    if (svc.excludeFromGatewayHostEnv) continue;
    lines.push(`      ${svc.envPrefix}_HOST: ${svc.composeName}`);
    lines.push(`      ${svc.envPrefix}_PORT: "${svc.defaultPort}"`);
  }
  return lines.join("\n");
}
