// Generated by backend/scripts/generate-instrument-universe.ts — do not hand-edit.
// Synthetic commodity futures appended to COMMODITY_ASSETS.

import type { RawCommoditySeed } from "./commodityAssets.ts";

export const GENERATED_COMMODITY_NAMES: Record<string, string> = {
  "ZL1!": "Soybean Oil Front Month",
  "ZM1!": "Soybean Meal Front Month",
  "ZO1!": "Oats Front Month",
  "ZR1!": "Rough Rice Front Month",
  "CC1!": "Cocoa Front Month",
  "OJ1!": "Orange Juice Front Month",
  "LBS1!": "Lumber Front Month",
  "HE1!": "Lean Hogs Front Month",
  "LE1!": "Live Cattle Front Month",
  "GF1!": "Feeder Cattle Front Month",
  "HO1!": "Heating Oil Front Month",
  "BZ1!": "Brent Crude Oil Front Month",
  "ALI1!": "Aluminum Front Month",
  "ZNC1!": "Zinc Front Month",
  "NIC1!": "Nickel Front Month",
  "TIN1!": "Tin Front Month",
  "URA1!": "Uranium Front Month",
  "EUA1!": "EU Carbon Allowance Front Month",
  "MW1!": "Hard Red Spring Wheat Front Month",
  "DA1!": "Class III Milk Front Month",
};

export const GENERATED_COMMODITIES: RawCommoditySeed[] = [
  { symbol: "ZL1!", initialPrice: 45, volatility: 0.018, sector: "Commodities/Agriculture", dailyVolume: 117047 },
  { symbol: "ZM1!", initialPrice: 320, volatility: 0.017, sector: "Commodities/Agriculture", dailyVolume: 158682 },
  { symbol: "ZO1!", initialPrice: 3.6, volatility: 0.02, sector: "Commodities/Agriculture", dailyVolume: 151322 },
  { symbol: "ZR1!", initialPrice: 17, volatility: 0.019, sector: "Commodities/Agriculture", dailyVolume: 163749 },
  { symbol: "CC1!", initialPrice: 8500, volatility: 0.03, sector: "Commodities/Agriculture", dailyVolume: 128774 },
  { symbol: "OJ1!", initialPrice: 340, volatility: 0.028, sector: "Commodities/Agriculture", dailyVolume: 38159 },
  { symbol: "LBS1!", initialPrice: 550, volatility: 0.035, sector: "Commodities/Materials", dailyVolume: 126228 },
  { symbol: "HE1!", initialPrice: 85, volatility: 0.022, sector: "Commodities/Agriculture", dailyVolume: 186313 },
  { symbol: "LE1!", initialPrice: 190, volatility: 0.016, sector: "Commodities/Agriculture", dailyVolume: 139998 },
  { symbol: "GF1!", initialPrice: 260, volatility: 0.017, sector: "Commodities/Agriculture", dailyVolume: 99989 },
  { symbol: "HO1!", initialPrice: 2.6, volatility: 0.024, sector: "Commodities/Energy", dailyVolume: 127404 },
  { symbol: "BZ1!", initialPrice: 82, volatility: 0.023, sector: "Commodities/Energy", dailyVolume: 170534 },
  { symbol: "ALI1!", initialPrice: 2300, volatility: 0.015, sector: "Commodities/Materials", dailyVolume: 56693 },
  { symbol: "ZNC1!", initialPrice: 2600, volatility: 0.017, sector: "Commodities/Materials", dailyVolume: 156997 },
  { symbol: "NIC1!", initialPrice: 17500, volatility: 0.024, sector: "Commodities/Materials", dailyVolume: 198877 },
  { symbol: "TIN1!", initialPrice: 26000, volatility: 0.02, sector: "Commodities/Materials", dailyVolume: 134989 },
  { symbol: "URA1!", initialPrice: 84, volatility: 0.03, sector: "Commodities/Energy", dailyVolume: 21259 },
  { symbol: "EUA1!", initialPrice: 65, volatility: 0.025, sector: "Commodities/Energy", dailyVolume: 30488 },
  { symbol: "MW1!", initialPrice: 6.8, volatility: 0.02, sector: "Commodities/Agriculture", dailyVolume: 177943 },
  { symbol: "DA1!", initialPrice: 18.4, volatility: 0.021, sector: "Commodities/Agriculture", dailyVolume: 33824 },
];
