import { describe, expect, it } from "vitest";
import { gridApi } from "../gridApi";

describe("gridApi – endpoint definitions", () => {
  it("uses gridApi as the reducer path", () => {
    expect(gridApi.reducerPath).toBe("gridApi");
  });

  it("exposes queryGrid query endpoint", () => {
    expect(gridApi.endpoints.queryGrid).toBeDefined();
  });

  it("builds a queryGrid request with the correct url and method", () => {
    // RTK Query internalises the query builder — verify the endpoint is registered
    expect(gridApi.endpoints.queryGrid).toBeDefined();
  });

  it("provides Grid tags for a query result", () => {
    const endpointDef = gridApi.endpoints.queryGrid as unknown as {
      matchFulfilled: unknown;
    };
    // matchFulfilled is generated by RTK when tag providers are configured
    expect(endpointDef.matchFulfilled).toBeDefined();
  });
});
